---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: books
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: gsacavdm/books:v1
        ports:
        - containerPort: 5000
