---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: books
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: gsacavdm/books:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: books
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: books
  type: LoadBalancer
